services:
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "password-manager-db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

networks:
  network_1:
    driver: bridge